### ISSUE TITLE
compile faild

### ISSUE THREAD

**Issue by langhuihui** [horhof/quickjs#5]
In file included from /usr/include/stdlib.h:24:0,
                 from qjs.c:25:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
Makefile:269: recipe for target '.obj/qjs.m32.o' failed
make: *** [.obj/qjs.m32.o] Error 1

**Comment by leecade** [comment]
comment the below line

```
# CONFIG_M32=y
```

**Comment by horhof** [comment]
https://www.freelists.org/list/quickjs-devel
