### ISSUE TITLE
Compile error on raspberry pi :   unrecognized command line option ‘-m32’

### ISSUE THREAD

**Issue by newghost** [horhof/quickjs#6]
gcc -m32 -g -Wall -MMD -MF .obj/qjs.m32.o.d -Wno-array-bounds -D_GNU_SOURCE -DCONFIG_VERSION=\"2019-07-09\" -O2 -flto -c -o .obj/qjs.m32.o qjs.c
    gcc: error: unrecognized command line option ‘-m32’

Remove all the '-m32' from the makefile, build pass.
Should make the '-m32' configurable?

**Comment by llgoer** [comment]
-m32 tells the compiler to use and create 32bit objects, in contrast to -m64 which would use/compile 64bit objects, and since the Pis ARM CPU only supports 32bit mode both flags were left out.

**Comment by horhof** [comment]
https://www.freelists.org/list/quickjs-devel
