### ISSUE TITLE
Include V8 and SpiderMonkey in Benchmarks

### ISSUE THREAD

**Issue by ohenepee** [horhof/quickjs#7]
This will give visitors an idea of how well it compares to existing browser js engines.

**Comment by aokihu** [comment]
I think the compare is needless, V8 is too BIG!!!, it can not install in embed device like esp32 etc. It’s only run on RPi,

**Comment by ohenepee** [comment]
I'm talking about its ability to be embedded...No! I'm talking about benchmark figures

**Comment by horhof** [comment]
https://www.freelists.org/list/quickjs-devel
