### ISSUE TITLE
multiple QuickJS projects?

### ISSUE THREAD

**Issue by davidmoshal** [horhof/quickjs#9]
are these the same project or different?

https://github.com/horhof/quickjs/
https://github.com/ldarren/QuickJS

**Comment by kevinkassimo** [comment]
These are all non-official mirrors. The original program is created by Fabrice Bellard and he does not use Github

**Comment by davidmoshal** [comment]
thanks, so how is it updated?

**Comment by lybvinci** [comment]
https://github.com/lybvinci/Adapter4QuickJs  this is build for android, could I have a link in your project?

**Comment by llgoer** [comment]
https://github.com/quickjs-zh/QuickJS

**Comment by horhof** [comment]
https://www.freelists.org/list/quickjs-devel
